sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t stephengrider/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephengrider/docker-react 
  
deployement:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "DockerApp"
  env: "Dockerapp-env"
  bucket_name: "elasticbeanstalk-us-west-2-573516256683"
  bucket_path: "DockerApp"
  on:
    banch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"  
  
